version: 2
updates:
- package-ecosystem: pnpm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 99
  versioning-strategy: increase
  target-branch: "main-v2"
